import { Montserrat } from 'next/font/google'
import './globals.css'
import { Providers } from "./redux/providers";


const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'FarmFuse',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
      <Providers>{children}</Providers>
      </body>
    </html>
  )
}
